config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :admin 
  resources :helper
  resources :attachments
  resources :category do 
    resources :tasks
  end
  
  #Client redirect upon signing in 
  get 'user_index' => 'user#index', as: :user_index
  get 'user_show/:id' => 'user#show', as: :user_show

  get 'tasks/:task_id/:client_id/show_task_info' => 'helper#show_task_info', as: :show_task_info

  get 'approve_status/:id' => 'admin#approve_status', as: :approve_status
  get 'reject_status/:id' => 'admin#reject_status', as: :reject_status

  get 'user_list' => 'admin#user_list', as: :user_list

  get 'category/:category_id/tasks/:id/accept_task' => 'tasks#accept_task', as: :accept_task

  get 'tasks/:task_id/user/:user_id/accept_helper' => 'tasks#accept_helper', as: :accept_helper

  get 'tasks/:task_id/complete_task' => 'tasks#complete_task', as: :complete_task
  
  get 'tasks/:task_id/finish_task' => 'tasks#finish_task', as: :finish_task

  get 'task/:id/helper/:user_id' => 'helper#show_applicant', as: :show_applicant

  get 'task/:id/helper/:helper_id/getrate' => 'helper#get_rate_helper', as: :get_rate_helper
  post 'task/:id/helper/:helper_id/patchrate' => 'helper#patch_rate_helper', as: :patch_rate_helper

  get 'task/:id/client/:client_id/getrate' => 'user#get_rate_client', as: :get_rate_client
  post 'task/:id/client/:client_id/patchrate' => 'user#patch_rate_client', as: :patch_rate_client

  get 'client_additional_info' => 'user#client_additional_info', as: :client_additional_info
  post 'patch/client_additional_info' => 'user#client_patch_additional_info', as: :client_patch_additional_info

  get 'helper_additional_info' => 'helper#helper_additional_info', as: :helper_additional_info
  post 'patch/helper_additional_info' => 'helper#helper_patch_additional_info', as: :helper_patch_additional_info

  post 'user/:id/deposit' => 'user#deposit', as: :deposit
  post 'user/:id/withdraw' => 'user#withdraw', as: :withdraw

end

app/views/admin/index.html.erb
<div class='adminIndexContainer'>
  <div class='aHeaderContainer'>
    <h1 class='aHeader'>Pending Users:</h1>
    <h1 class='aPendingCount'><%= @users.where(:user_status => 'Pending').count %></h1>
  </div>

  <div>
    <hr class='aLine'>
  </div>

  <div class='aContainer'>
    <% @users.each do |user| %>
      <% if user.user_status == 'Pending' %>
        <div class='aPendingUsers'>
          <div class='aPendingNamesContainer'>
            <p><img src="../assets/user_solid.png"/></p>
            <p class='aPendingNames'><%= user.first_name %></p>
            <p class='aPendingNames'><%= user.last_name %></p>
          </div>

          <h2 class="aDetails ">
            <%= link_to 'Details', admin_path(user.id), class: "aDetailsButton" %>
          </h2>
        </div>
      <% end %>
    <% end %>
  </div>    
</div>

app/views/admin/show.html.erb

<div class='adminIndexContainer'>
  <div class='aHeaderContainer'>
    <h2 class='aHeader'>User Information</h2>
  </div>
  <div>
    <hr class='aLine'>
  </div>
    
  <div class='aUserContainer'>
    <div>
      <img src="../assets/user_proxy_picture.png"/>
    </div>

    <div class='aInfoContainer'>
      <div class='aDetailContainer'>
        <p class='aInfoLabel'>First Name:</p>
        <p class='aInfoDetail'><%= @user.first_name %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Last Name: </p> 
        <p class='aInfoDetail'><%= @user.last_name %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Email: </p>
        <p class='aInfoDetail'><%= @user.email %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Mobile Number: </p>
        <p class='aInfoDetail'><%= @user.mobile_number %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>User Type: </p>
        <p class='aInfoDetail'> 
          <% if @user.helper == true %>
              Helper 
          <% else %> 
              Client
          <% end %>
        </p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Status: </p>
        <p class='aInfoDetail'><%= @user.user_status %></p>
      </div>

      <div  class='aDetailContainer'>
          <p class='aInfoLabel'>Balance: </p>
          <p class='aInfoDetail'><%= @user.balance %></p>
      </div>

      <div  class='aDetailContainer'>
        <p class='aInfoLabel'>Rating: </p>
        <p class='aInfoDetail'>
          <% array = @user.rating.to_a %>
            <% if array.length == 0 %>
                <% ave = 0 %>
            <% else %>
                <% ave = array.sum/array.length %>
            <% end %>
            <%= ave %>/5
        </p>
      </div>
    </div>

      <% if @user.attachments.first == nil %>
      <% else %>
        <%= image_tag @user.attachments.first.image.to_s %>
      <% end %>

      <div class='aStatBtnContainer'>
        <% if @user.user_status == "Pending"%>
          <p class='aPendingButtons'><%= link_to 'Approve', approve_status_path(@user), class: 'aApproveBtn' %></p>
          <p class='aPendingButtons'><%= link_to 'Reject', reject_status_path(@user), class: 'aRejectBtn' %></p>
        <% end %> 
      </div>

      <% if @user.user_status == "Pending" %>
        <%= link_to 'Back', root_path %>
      <% else @user.user_status == "Approved" %>
        <%= link_to 'Back', user_list_path %>
      <% end %>
  </div>
</div>

app/views/admin/user_list.html.erb
<div class='aApprovedContainer'>  
  <div class='aFloatContainer'>
    <div class='aSwitchContainer'>
      <div id="slider"></div>
      <button type="button" class="aToggleBtn" id='bClient' onclick="Client()">CLIENTS</button>
      <button type="button" class="aToggleBtn" id='bHelper' onclick="Helper()"> HELPERS</button>   
    </div>

    <div class='aLineBreak'>
      <hr class='aLine'>
    </div>

    <div class='aUserTypeContainer' id='client'>   
      <div class='aContainer'>
        <% @user.each do |user| %>
          <% if user.user_status == 'Approved' && user.admin == false && user.helper == false %>
            <div class='aApprovedUsers'>
              <div class='aApprovedNamesContainer'>
                <p><img src="../assets/user_solid.png"/></p>
                <p class='aApprovedNames'><%= user.first_name %></p> 
                <p class='aApprovedNames'><%= user.last_name %></p>
              </div>
                <p class='aInfo'>
                  <%= link_to  admin_path(user.id) do %>
                    <img src="../assets/info.png"/>
                  <% end %>
                </p>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
      <div class='aUserTypeContainer' id='helper'>   
        <div class='aContainer'>
          <% @user.each do |user| %>
            <% if user.user_status == 'Approved' && user.helper %>
              <div class='aApprovedUsers'>
                <div class='aApprovedNamesContainer'>
                  <p><img src="../assets/user_solid.png"/></p>
                  <p class='aApprovedNames'><%= user.first_name %></p> 
                  <p class='aApprovedNames'><%= user.last_name %></p>
                </div>
              </div>
              <p class='aInfo'>
                <%= link_to admin_path(user.id) do %>
                  <img src="../assets/info.png"/>
                <% end %>
              </p>
            <% end %>
          <% end %>
        </div>
      </div>
  </div>
</div>

<script>
  var client = document.getElementById("client");
  var helper = document.getElementById("helper");
  var slider = document.getElementById("slider");
  var bclient = document.getElementById("bClient");
  var bhelper = document.getElementById("bHelper");

  function Helper () {
    client.style.opacity = '0';
    helper.style.opacity = '1';
    slider.style.left = '50%';
    bhelper.style.color = 'white'
    bclient.style.color = 'black'
  }

  function Client () {
    client.style.opacity = '1';
    helper.style.opacity = '0';
    slider.style.left = '0';
    bhelper.style.color = 'black'
    bclient.style.color = 'white'
  }
</script>