config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :admin 
  resources :helper
  resources :attachments
  resources :category do 
    resources :tasks
  end
  
  #Client redirect upon signing in 
  get 'user_index' => 'user#index', as: :user_index
  get 'user_show/:id' => 'user#show', as: :user_show

  get 'tasks/:task_id/:client_id/show_task_info' => 'helper#show_task_info', as: :show_task_info

  get 'approve_status/:id' => 'admin#approve_status', as: :approve_status
  get 'reject_status/:id' => 'admin#reject_status', as: :reject_status

  get 'user_list' => 'admin#user_list', as: :user_list

  get 'category/:category_id/tasks/:id/accept_task' => 'tasks#accept_task', as: :accept_task

  get 'tasks/:task_id/user/:user_id/accept_helper' => 'tasks#accept_helper', as: :accept_helper

  get 'tasks/:task_id/complete_task' => 'tasks#complete_task', as: :complete_task
  
  get 'tasks/:task_id/finish_task' => 'tasks#finish_task', as: :finish_task

  get 'task/:id/helper/:user_id' => 'helper#show_applicant', as: :show_applicant

  get 'task/:id/helper/:helper_id/getrate' => 'helper#get_rate_helper', as: :get_rate_helper
  post 'task/:id/helper/:helper_id/patchrate' => 'helper#patch_rate_helper', as: :patch_rate_helper

  get 'task/:id/client/:client_id/getrate' => 'user#get_rate_client', as: :get_rate_client
  post 'task/:id/client/:client_id/patchrate' => 'user#patch_rate_client', as: :patch_rate_client

  get 'client_additional_info' => 'user#client_additional_info', as: :client_additional_info
  post 'patch/client_additional_info' => 'user#client_patch_additional_info', as: :client_patch_additional_info

  get 'helper_additional_info' => 'helper#helper_additional_info', as: :helper_additional_info
  post 'patch/helper_additional_info' => 'helper#helper_patch_additional_info', as: :helper_patch_additional_info

  post 'user/:id/deposit' => 'user#deposit', as: :deposit
  post 'user/:id/withdraw' => 'user#withdraw', as: :withdraw

end

app/controllers/helper_controller.rb
class HelperController < ApplicationController
  def index
    @users = User.all
    @categories = Category.all
    @tasks = Task.all
  end

  def show
    @user = User.find(params[:id])
    @categories = Category.all
    @task = Task.all
  end

  def show_applicant
    @user = User.find(params[:user_id])
    @task = Task.all
    @task_id = Task.find(params[:id])
  end

  def get_rate_helper
    @task = Task.find(params[:id])
    @helper = User.find(params[:helper_id])
  end
  
  def patch_rate_helper
    @task = Task.find(params[:id])
    @helper = User.find(params[:helper_id])

    @array = @helper.rating.to_a
    input = params[:input_rating].to_i
    @array.push(input)
    @helper.update(rating: @array)
    @helper.save!

    @task.update(rated_by_client: true)
    @task.save!
    redirect_to user_index_path(@task.client_id)
  end

  def show_task_info
    @task = Task.find(params[:task_id])
    @client = User.find(params[:client_id])
    @category = Category.all
  end

  def helper_additional_info
    @user = current_user
  end

  def helper_patch_additional_info
    @user = current_user
    @user.update(mobile_number: params[:mobile_number])
    @user.save!
    redirect_to user_index_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attachments_helper.rb
module AttachmentsHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/helper_helper.rb
module HelperHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/helper/get_rate_helper.html.erb
<div class='tIndexContainer'>
  <div class='tHeaderContainer'>
    <h2 class='tHeader'><%= @task.name %></h2>
  </div>

  <div>
    <hr class='aLine'>
  </div>

  <div class='tTaskContainer'>
    <div class='tInfoContainer'>
      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Details:</p>
        <p class='aInfoDetail'><%= @task.details %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Date:</p>
        <p class='aInfoDetail'><%= @task.date %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Rate:</p>
        <p class='aInfoDetail'><%= @task.hourly_rate %></p>
      </div>

      <p class='aInfoLabel'>Helper Information</p>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'> Name:</p>
        <p class='aInfoDetail'><%= @helper.first_name + ' ' + @helper.last_name %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Email:</p>
        <p class='aInfoDetail'><%= @helper.email %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Mobile Number:</p>
        <p class='aInfoDetail'><%= @helper.mobile_number %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Rating:</p>
        <p class='aInfoDetail'> 
          <% array = @helper.rating.to_a %>
            <% if array.length == 0 %>
              <% ave = 0 %>
            <% else %>
              <% ave = array.sum/array.length %>
            <% end %>
            <%= ave %>/5
        </p>
      </div>
    </div>

    <%= form_with url: patch_rate_helper_path do |f| %>
      <div class="field">
          <h6><%= f.label 'Rating' %><br/></h6>
          <%= f.number_field :input_rating %>
          <%= f.submit "Submit" %>
      </div>
    <% end %>

    </div>
      <%= link_to 'Back' , :back %>
    </div>
  </div>

<script>
  var modal = document.getElementById("catForm");
  var modal2 = document.getElementById("catForm2");
  var button = document.getElementById("editBtn");
  var button2 = document.getElementById("deleteBtn");
  var close = document.getElementsByClassName("close")[0];
  var close2 = document.getElementsByClassName("close")[1];

  button.onclick = function() {
    modal.style.display = "block";
  }

  button2.onclick = function() {
    modal2.style.display = "block";
  }

  close.onclick = function() {
    modal.style.display = "none";
  }

  close2.onclick = function() {
    modal2.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    } else if (event.target == modal2) {
      modal2.style.display = "none";
    }
  }
</script>

app/views/helper/helper_additional_info.html.erb
<%= form_with url: helper_patch_additional_info_path do |f| %>
  <div class="field">
    <%= f.label :mobile_number %><br />
    <%= f.text_field :mobile_number%>
  </div>

  <div class="actions">
    <%= f.submit 'Update' %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image%>
  </div>

  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/helper/index.html.erb
<div class='uIndexContainer'>
  <div class='uFloatContainer'>
    <div class='uSwitchContainer'>
      <div id="slideBtn"></div>
      <button type="button" class="uToggleBtn" id='bOpen' onclick="Open()">Applied Tasks</button>
      <button type="button" class="uToggleBtn" id='bOnGoing' onclick="Going()">On-going Tasks</button>
      <button type="button" class="uToggleBtn" id='bHistory' onclick="History()">Completed</button>
    </div>

    <div class='uLineBreak'>
      <hr class='aLine'>
    </div>

    <div class='uTaskHeaderContainer'>
      <p class='uTaskHeader'>Task</p>
      <p class='uTaskHeader'>Date</p>
      <p class='uTaskHeader'>Rate</p>
      <p class='uTaskHeader'>Action</p>
    </div>

    <div class='uLineBreak'>
      <hr class='aLine'>
    </div>
  
    <div class='uAllTasksContainer' id='open'>
      <% @tasks.each do |task|%>
        <% array = task.helper_applicants.to_a %>
        <% if array.include?(current_user.id) == true && task.helper_id == nil%>                     
          <div class='uTasks'>
              <p class='uTaskLabels'><%= task.name %></p>
              <p class='uTaskLabels'><%= task.date %></p>
              <p class='uTaskLabels'><%= task.hourly_rate %></p>
              <p class='uTaskView' id='uViewTask'>
                  <%= link_to 'View', show_task_info_path(task.id, task.client_id)   , class: 'uTaskViewBtn'%>
              </p>  
          </div>
        <%end%>
      <%end%>
    </div>

    <div class='uAllTasksContainer' id='onGoing'>
      <% @tasks.each do |task|%>
        <% if task.helper_id == current_user.id && task.task_status == "Approved" %>
          <div class='uTasks'>
            <p class='uTaskLabels'><%= task.name %></p>
            <p class='uTaskLabels'><%= task.date %></p>
            <p class='uTaskLabels'><%= task.hourly_rate %></p>
            <p class='uTaskView' id='uViewTask'>
                <%= link_to 'Complete', complete_task_path(task.id), class: 'uTaskViewBtn'%>
            </p>
          </div>
        <%end%>
      <%end%> 
    </div>

    <div class='uAllTasksContainer' id='history'>
      <% @tasks.each do |task|%>
        <% if task.helper_id == current_user.id && task.task_status == "Completed" || task.helper_id == current_user.id && task.task_status == "Finished" %>
          <div class='uTasks'>   
            <p class='uTaskLabels'><%= task.name %></p>
            <p class='uTaskLabels'><%= task.date %></p>
            <p class='uTaskLabels'><%= task.hourly_rate %></p>
            <p class='uTaskView' id='uViewTask'>
              <% if task.rated_by_helper? %>
                  <td>Done</td>
              <% else %>
                  <%= link_to 'Rate', get_rate_client_path(task.id, task.client_id), class: 'uTaskViewBtn'%>
              <%end%>
            </p>
          </div>
        <%end%>
      <%end%> 
    </div>
  </div>
</div>

<script>
  var open = document.getElementById("open");
  var onGoing = document.getElementById("onGoing");
  var done = document.getElementById("history");
  var slideBtn = document.getElementById("slideBtn");
  var bOpen = document.getElementById("bOpen");
  var bOnGoing = document.getElementById("bOnGoing");
  var bHistory = document.getElementById("bHistory");
  var applicantListModal = document.getElementById("applicantsForm");
  var applicantListBtn = document.getElementById('listApplicantsBtn');
  var applicantListClose = document.getElementsByClassName("close")[0];

  function Open () {
    open.style.display = 'block';
    onGoing.style.display = 'none';
    done.style.display = 'none';
    slideBtn.style.left = '0%';
    bOpen.style.color = 'white'
    bOnGoing.style.color = 'black'
    bHistory.style.color = 'black'
  }

  function Going () {
    open.style.display = 'none';
    onGoing.style.display = 'block';
    done.style.display = 'none';
    slideBtn.style.left = '33.3%';
    bOpen.style.color = 'black'
    bOnGoing.style.color = 'white'
    bHistory.style.color = 'black'
  }

  function History () {
    open.style.display = 'none';
    onGoing.style.display = 'none';
    done.style.display = 'block';
    slideBtn.style.left = '67.3%';
    bOpen.style.color = 'black'
    bOnGoing.style.color = 'black'
    bHistory.style.color = 'white'
  }

  applicantListBtn.onclick = function() {
    applicantListModal.style.display = "block";
  }

  applicantListClose.onclick = function() {
    applicantListModal.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target == applicantListModal) {
      applicantListModal.style.display = "none";
    }
  }
</script>

app/views/helper/old_get_rate_helper.html.erb
<h1><center>Rate Helper</center></h1>
<h3><%= @task.name %></h3>

<h6>Task details</h6>
  <p><%= @task.details %></p>

<h6>Rate</h6>
  <p><%= @task.hourly_rate %></p>

<h6>Helper email</h6>
  <p><%= @helper.email %></p>

<%= form_with url: patch_rate_helper_path do |f| %>
  <div class="field">
    <h6><%= f.label 'Rating' %><br/></h6>
    <%= f.number_field :input_rating %>
    <%= f.submit "Submit" %>
  </div>
<% end %>

app/views/helper/show.html.erb
<% if current_user.admin || current_user.helper %>
	<div class="container h-2/4 flex justify-center items-center ">
		<h5><%= @user.first_name %> <%= @user.last_name %></h5>
		<h5><%= @user.email %></h5>
		<h5><%= @user.balance %></h5>
		<br>

		<h3>Current Balance</h3>
			<h5><%= @user.balance %></h5>
			<h3> Withdraw Money </h3>

		<%= form_with url: withdraw_path do |f| %>
			<div class="field">
				<%= f.label :amount %><br/>
				<%= f.number_field :amount %>
			</div>   

			<div class="actions">
				<%= f.submit "Withdraw" %>
			</div>
		<% end %>
		<br>
		<br>
		<%= link_to 'Back', :back %>
	</div>

<% else %>   

	<div class="container h-2/4 flex justify-center items-center ">
		<h5><%= @user.first_name %> <%= @user.last_name %></h5>
		<p><%= @user.email %></p>
		<p><%= @user.balance %></p>
		<p><%= @user.mobile_number %></p>
		<h5>hidden bal</h5>
		<br>
		<%= link_to 'Back', :back %>
	</div>
<% end %>

app/views/helper/show_applicant.html.erb
<div class="container h-2/4 flex justify-center items-center ">
  <h5><%= @user.first_name %></h5>
  <h5><%= @user.last_name %></h5>
  <h5><%= @user.email %></h5>
  <br>
  <td><%= link_to 'Accept', accept_helper_path(@task_id, @user.id), class: "btn btn-outline-dark btn-sm" %></td>
  <%= link_to 'Back', :back %>
</div>

app/views/helper/show_task_info.html.erb
<div class='tIndexContainer'>
  <div class='tHeaderContainer'>
    <h2 class='tHeader'><%= @task.name %></h2>
  </div>

  <div>
    <hr class='aLine'>
  </div>

  <div class='tTaskContainer'>
    <div class='tInfoContainer'>
      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Details:</p>
        <p class='aInfoDetail'><%= @task.details %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Date:</p>
        <p class='aInfoDetail'><%= @task.date %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Rate:</p>
        <p class='aInfoDetail'><%= @task.hourly_rate %></p>
      </div>

      <div id='task_longitude'>
        <%= @task.longitude %>
      </div>

      <div id='task_latitude'>
        <%= @task.latitude %>
      </div>
    </div>

    <p class='aInfoLabel'>Client Information</p>
    <div>
      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Name:</p>
        <p class='aInfoDetail'><%= @client.first_name + ' ' + @client.last_name %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Email:</p>
        <p class='aInfoDetail'><%= @client.email %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Mobile Number:</p>
        <p class='aInfoDetail'><%= @client.mobile_number %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Rating:</p>
        <p class='aInfoDetail'> 
          <% array = @client.rating.to_a %>
          <% if array.length == 0 %>
            <% ave = 0 %>
          <% else %>
            <% ave = array.sum/array.length %>
          <% end %>
          <%= ave %>/5
        </p>
      </div>
    </div>

    <div>
      <% if current_user.helper? %>
        <%= link_to 'Apply', accept_task_path(@task.category_id, @task), class: "btn btn-outline-dark btn-sm" %>
      <% elsif current_user.admin == false && current_user.helper == false && @task.helper_id = nil%>
        <%= link_to 'Edit', edit_category_task_path(@task.category_id, @task.id), class: "btn btn-outline-dark btn-sm" %>
        <%= link_to 'Delete', category_task_path(@task.category_id, @task.id),method: :delete, class: "btn btn-outline-dark btn-sm" %></td>
      <% else %>
      <% end %>
    </div>
    <%= link_to 'Back' , :back %>
  </div>
</div>

<script>
  var modal = document.getElementById("catForm");
  var modal2 = document.getElementById("catForm2");
  var button = document.getElementById("editBtn");
  var button2 = document.getElementById("deleteBtn");
  var close = document.getElementsByClassName("close")[0];
  var close2 = document.getElementsByClassName("close")[1];

  button.onclick = function() {
    modal.style.display = "block";
  }

  button2.onclick = function() {
    modal2.style.display = "block";
  }

  close.onclick = function() {
    modal.style.display = "none";
  }

  close2.onclick = function() {
    modal2.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    } else if (event.target == modal2) {
      modal2.style.display = "none";
    }
  }
</script>