config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :admin 
  resources :helper
  resources :attachments
  resources :category do 
    resources :tasks
  end
  
  #Client redirect upon signing in 
  get 'user_index' => 'user#index', as: :user_index
  get 'user_show/:id' => 'user#show', as: :user_show

  get 'tasks/:task_id/:client_id/show_task_info' => 'helper#show_task_info', as: :show_task_info

  get 'approve_status/:id' => 'admin#approve_status', as: :approve_status
  get 'reject_status/:id' => 'admin#reject_status', as: :reject_status

  get 'user_list' => 'admin#user_list', as: :user_list

  get 'category/:category_id/tasks/:id/accept_task' => 'tasks#accept_task', as: :accept_task

  get 'tasks/:task_id/user/:user_id/accept_helper' => 'tasks#accept_helper', as: :accept_helper

  get 'tasks/:task_id/complete_task' => 'tasks#complete_task', as: :complete_task
  
  get 'tasks/:task_id/finish_task' => 'tasks#finish_task', as: :finish_task

  get 'task/:id/helper/:user_id' => 'helper#show_applicant', as: :show_applicant

  get 'task/:id/helper/:helper_id/getrate' => 'helper#get_rate_helper', as: :get_rate_helper
  post 'task/:id/helper/:helper_id/patchrate' => 'helper#patch_rate_helper', as: :patch_rate_helper

  get 'task/:id/client/:client_id/getrate' => 'user#get_rate_client', as: :get_rate_client
  post 'task/:id/client/:client_id/patchrate' => 'user#patch_rate_client', as: :patch_rate_client

  get 'client_additional_info' => 'user#client_additional_info', as: :client_additional_info
  post 'patch/client_additional_info' => 'user#client_patch_additional_info', as: :client_patch_additional_info

  get 'helper_additional_info' => 'helper#helper_additional_info', as: :helper_additional_info
  post 'patch/helper_additional_info' => 'helper#helper_patch_additional_info', as: :helper_patch_additional_info

  post 'user/:id/deposit' => 'user#deposit', as: :deposit
  post 'user/:id/withdraw' => 'user#withdraw', as: :withdraw

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :is_user_admin, :is_user_helper, :is_user_client

  def index
    redirect_to new_user_session_path
  end

  private
  def is_user_admin
    if current_user.present? && current_user.admin
      redirect_to admin_index_path
    end
  end

  def is_user_helper
    if current_user.present? && current_user.helper == true && current_user.mobile_number == nil
      redirect_to helper_additional_info_path
    elsif current_user.present? && current_user.helper == true
      redirect_to helper_index_path
    end
  end

  def is_user_client
    if current_user.present? && current_user.helper == false && current_user.mobile_number == nil
      redirect_to client_additional_info_path
    elsif current_user.present? && current_user.helper == false
      redirect_to user_index_url
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<% if user_signed_in? %>
  <nav class="desktopNavbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>   
      <div class="collapse navbar-collapse" id="navbarSupportedContent">   
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <% if current_user.admin %>
            <li class="nav-item">
              <%= link_to 'Pending Users', root_path, class:'nav-link'%>
            </li>

            <li class="nav-item">
              <%= link_to 'Approved Users', user_list_path, class:'nav-link'%>
            </li>
            
            <li class="nav-item">
              <%= link_to 'Category', category_index_path, class:'nav-link'%>
            </li>

            <li class="nav-item">
              <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:'nav-link'%>
            </li>

          <% elsif current_user.helper %>
            <% if current_user.mobile_number == nil %>
              <li class="nav-item">
                <%= link_to 'Update Account', edit_user_registration_path, class:'nav-link'%>
              </li>

              <li class="nav-item">
                <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:'nav-link'%>
              </li>

            <% else %>

              <li class="nav-item">
                <%= link_to 'Home', helper_index_path, class:'nav-link'%>
              </li>

              <li class="nav-item">
                <%= link_to 'Category', category_index_path(params[:id]), class:'nav-link'%>
              </li>

              <li class="nav-item">
                  <%= link_to 'Account', helper_path(current_user), class:'nav-link' %>
                </li>  

              <li class="nav-item">
                <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:'nav-link'%>
              </li>
            <% end %>
            <% else %>
              <% if current_user.mobile_number == nil %>
                <li class="nav-item">
                  <%= link_to 'Update Account', edit_user_registration_path, class:'nav-link'%>
                </li>

                <li class="nav-item">
                  <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:'nav-link'%>
                </li>
              <% else %>
                <li class="nav-item">
                  <%= link_to 'Home', user_index_url, class:'nav-link'%>
                </li>

                <li class="nav-item">
                  <%= link_to 'Category', category_index_path(params[:id]), class:'nav-link'%>
                </li>

                <li class="nav-item">
                  <%= link_to 'My Account', user_show_path(current_user), class:'nav-link' %>
                </li> 

                <li class="nav-item">
                  <%= button_to 'Sign out', destroy_user_session_path, method: :delete, class:'nav-link'%>
                </li>
              <% end %>
            <% end %>
        </ul>
      </div>
    </div>
  </nav>
<% end %>

app/views/home/index.html.erb
<h1><center><marquee>Handy Bunny</marquee></center></h1>