config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  devise_for :users
  resources :admin 
  resources :helper
  resources :attachments
  resources :category do 
    resources :tasks
  end
  
  #Client redirect upon signing in 
  get 'user_index' => 'user#index', as: :user_index
  get 'user_show/:id' => 'user#show', as: :user_show

  get 'tasks/:task_id/:client_id/show_task_info' => 'helper#show_task_info', as: :show_task_info

  get 'approve_status/:id' => 'admin#approve_status', as: :approve_status
  get 'reject_status/:id' => 'admin#reject_status', as: :reject_status

  get 'user_list' => 'admin#user_list', as: :user_list

  get 'category/:category_id/tasks/:id/accept_task' => 'tasks#accept_task', as: :accept_task

  get 'tasks/:task_id/user/:user_id/accept_helper' => 'tasks#accept_helper', as: :accept_helper

  get 'tasks/:task_id/complete_task' => 'tasks#complete_task', as: :complete_task
  
  get 'tasks/:task_id/finish_task' => 'tasks#finish_task', as: :finish_task

  get 'task/:id/helper/:user_id' => 'helper#show_applicant', as: :show_applicant

  get 'task/:id/helper/:helper_id/getrate' => 'helper#get_rate_helper', as: :get_rate_helper
  post 'task/:id/helper/:helper_id/patchrate' => 'helper#patch_rate_helper', as: :patch_rate_helper

  get 'task/:id/client/:client_id/getrate' => 'user#get_rate_client', as: :get_rate_client
  post 'task/:id/client/:client_id/patchrate' => 'user#patch_rate_client', as: :patch_rate_client

  get 'client_additional_info' => 'user#client_additional_info', as: :client_additional_info
  post 'patch/client_additional_info' => 'user#client_patch_additional_info', as: :client_patch_additional_info

  get 'helper_additional_info' => 'helper#helper_additional_info', as: :helper_additional_info
  post 'patch/helper_additional_info' => 'helper#helper_patch_additional_info', as: :helper_patch_additional_info

  post 'user/:id/deposit' => 'user#deposit', as: :deposit
  post 'user/:id/withdraw' => 'user#withdraw', as: :withdraw

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  #  :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable

  validates :first_name, presence: true, length: {minimum: 3}, format: { with: /\A[a-zA-Z]+\z/, message: "can only include letters"}
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "can only include letters"}

  has_many :categories, dependent: :destroy
  has_many :attachments, dependent: :destroy
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_action :is_admin
  before_action :is_helper, except: [:show, :get_rate_client, :patch_rate_client]

  def index 
    @users = User.all
    @categories = Category.all
    @tasks = Task.all
  end

  def show
    @user = User.find(params[:id])
    @balance = current_user.balance
  end

  def destroy
  end

  def deposit
    user = current_user
    user.balance += params[:amount].to_i
    @balance = current_user.balance
    user.save
    @amount = params[:amount].to_i
  end

  def withdraw
    user = current_user
    user.balance -= params[:amount].to_i
    @balance = current_user.balance
    user.save
  end

  def get_rate_client
    @task = Task.find(params[:id])
    @client = User.find(params[:client_id])
  end
  
  def patch_rate_client
    @task = Task.find(params[:id])
    @client = User.find(params[:client_id])

    @array = @client.rating.to_a
    input = params[:input_rating].to_i
    @array.push(input)
    @client.update(rating: @array)
    @client.save!

    @task.update(rated_by_helper: true)
    @task.save!
    redirect_to user_index_path(@task.helper_id)
  end

  def client_additional_info
    @user = current_user
    @attachment = Attachment.new
  end

  def client_patch_additional_info
    @attachment = Attachment.create!(image: params[:image], user_id: current_user.id)
    @user = current_user
    @user.update(mobile_number: params[:mobile_number])
    @user.save!
    redirect_to user_index_path
  end

  private

  def is_admin
    if authenticate_user! && current_user.admin
      redirect_to root_path
    end
  end

  def is_helper
    if authenticate_user! && current_user.helper
      redirect_to root_path
    end
  end
end

app/views/user/client_additional_info.html.erb
<%= form_with url: client_patch_additional_info_path do |f| %>
  <div class="field">
    <%= f.label :mobile_number %><br />
    <%= f.text_field :mobile_number%>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.file_field :image%>
  </div>
  
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user/deposit.html.erb
<h1>Receipt</h1>
<h2> Your transaction was successful!</h2>
<h2>You deposited PHP<%= @amount %></h2> 
<h2>Your new balance is PHP<%= @balance %> </h2>

<br><br>
<%= link_to 'Back', :back %>

app/views/user/get_rate_client.html.erb
<div class='tIndexContainer'>
  <div class='tHeaderContainer'>
    <h2 class='tHeader'><%= @task.name %></h2>
  </div>

  <div>
    <hr class='aLine'>
  </div>

  <div class='tTaskContainer'>
    <div class='tInfoContainer'>
      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Details:</p>
        <p class='aInfoDetail'><%= @task.details %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Date:</p>
        <p class='aInfoDetail'><%= @task.date %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Rate:</p>
        <p class='aInfoDetail'><%= @task.hourly_rate %></p>
      </div>

      <p class='aInfoLabel'>Client Information</p>

        <div class='aDetailContainer'>
          <p class='aInfoLabel'> Name:</p>
          <p class='aInfoDetail'><%= @client.first_name + ' ' + @client.last_name %></p>
        </div>

        <div class='aDetailContainer'>
          <p class='aInfoLabel'>Email:</p>
          <p class='aInfoDetail'><%= @client.email %></p>
        </div>

        <div class='aDetailContainer'>
          <p class='aInfoLabel'>Mobile Number:</p>
          <p class='aInfoDetail'><%= @client.mobile_number %></p>
        </div>

        <div class='aDetailContainer'>
          <p class='aInfoLabel'>Rating:</p>
          <p class='aInfoDetail'> 
            <% array = @client.rating.to_a %>
            <% if array.length == 0 %>
              <% ave = 0 %>
            <% else %>
              <% ave = array.sum/array.length %>
            <% end %>
            <%= ave %>/5
          </p>
        </div>
      </div>

      <%= form_with url: patch_rate_client_path do |f| %>
        <div class="field">
          <h6><%= f.label 'Rating' %><br/></h6>
          <%= f.number_field :input_rating %>
          <%= f.submit "Submit" %>
        </div>
      <% end %>

      </div>
        <%= link_to 'Back' , :back %>
      </div>
    </div>

<script>
  var modal = document.getElementById("catForm");
  var modal2 = document.getElementById("catForm2");
  var button = document.getElementById("editBtn");
  var button2 = document.getElementById("deleteBtn");
  var close = document.getElementsByClassName("close")[0];
  var close2 = document.getElementsByClassName("close")[1];

  button.onclick = function() {
    modal.style.display = "block";
  }

  button2.onclick = function() {
    modal2.style.display = "block";
  }

  close.onclick = function() {
    modal.style.display = "none";
  }

  close2.onclick = function() {
    modal2.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target == modal) {
      modal.style.display = "none";
    } else if (event.target == modal2) {
      modal2.style.display = "none";
    }
  }
</script>

app/views/user/index.html.erb
<div class='uIndexContainer'>
  <div class='uFloatContainer'>
    <div class='uSwitchContainer'>
      <div id="slideBtn"></div>
      <button type="button" class="uToggleBtn" id='bOpen' onclick="Open()">Open Tasks</button>
      <button type="button" class="uToggleBtn" id='bOnGoing' onclick="Going()">On-going Tasks</button>
      <button type="button" class="uToggleBtn" id='bHistory' onclick="History()">Completed</button>
    </div>

    <div class='uLineBreak'>
      <hr class='aLine'>
    </div>

    <div class='uTaskHeaderContainer'>
      <p class='uTaskHeader'>Task</p>
      <p class='uTaskHeader'>Date</p>
      <p class='uTaskHeader'>Helper</p>
      <p class='uTaskHeader'>Details</p>
    </div>

    <div class='uLineBreak'>
      <hr class='aLine'>
    </div>
    
    <div class='uAllTasksContainer' id='open'>
      <% @tasks.each do |task|%>
        <% if task.created_by == current_user.first_name + ' ' + current_user.last_name && task.helper_id == nil%>
          <div class='uTasks'>
            <p class='uTaskLabels'><%= task.name %></p>
            <p class='uTaskLabels'><%= task.date %></p>
            <% if task.helper_applicants == [] %>
                <p class='uTaskLabels'>No Helper Applicants</p>
            <% else %>
              <button class='uTaskView' id='listApplicantsBtn'> 
                <% if task.helper_applicants.count == 1 %>  
                  <%= task.helper_applicants.count %> Helper
                <% else %>
                  <%= task.helper_applicants.count %> Helpers
                <% end %>
              </button>
            <% end %>

            <div class='uApplicantContainer' id='applicantsForm'>
              <div class='uFormApp'>
                <div class='uAppHeader'>
                  <div></div>
                  <img src='../assets/close.png' class="close"/>
                </div>

                <h2>List of Applicants</h2>

                <div class='uPerApp'>
                  <p class='uTaskLabels'>No.</p>
                  <p class='uTaskLabels'>Applicant's Name</p>
                  <p class='uTaskLabels'>Rating</p>
                  <p class='uTaskLabels'></p>
                </div>

                <div class='uAppsShow'>        
                  <% ids = task.helper_applicants.to_a %>
                  <% task_id = task.id%>
                  <% @count = 0 %>
                  <% ids.each do |id|%>
                    <div class='uPerApp'>
                      <p class='uTaskLabels'><%= @count += 1 %></p>
                      <p class='uTaskLabels'><%= User.find(id).first_name %> <%= User.find(id).last_name %></p>
                      <% array = User.find(id).rating.to_a %>
                      <p class='uTaskLabels'>
                        <% if array.length == 0 %>
                          <% ave = 0 %>
                        <% else %>
                          <% ave = array.sum/array.length %>
                        <% end %>
                      <p class='uTaskLabels'><%= link_to 'Accept', accept_helper_path(task_id, id), class: "btn btn-outline-dark btn-sm" %></p>
                    </div>
                  <% end %>           
                </div>
              </div>
            </div>
            <% end %> 
            <p class='uTaskView' id='uViewTask'>
              <%= link_to 'View', show_task_info_path(task.id, task.client_id) , class: 'uTaskViewBtn'%>
            </p>  
          </div>
        <%end%>
      <%end%>

    </div>
      <div class='uAllTasksContainer' id='onGoing'>
        <% @tasks.each do |task|%>
          <% if task.created_by == current_user.first_name + ' ' + current_user.last_name && task.task_status == "Approved" %>
            <div class='uTasks'>
              <p class='uTaskLabels'><%= task.name %></p>
              <p class='uTaskLabels'><%= task.date %></p>
              <p class='uTaskLabels'><%= User.find(task.helper_id).first_name %> <%= User.find(task.helper_id).last_name %></p> 
              <p class='uTaskView' id='uViewTask'>
                <%= link_to 'View', show_task_info_path(task.id, task.client_id), class: 'uTaskViewBtn'%>
              </p>  
            </div>
          <%end%>
        <%end%> 
      </div>

      <div class='uAllTasksContainer' id='history'>
        <% @tasks.each do |task|%>
          <% if task.created_by == current_user.first_name + ' ' + current_user.last_name && task.task_status == "Completed" || task.task_status == "Finished" %>
            <div class='uTasks'>
              <p class='uTaskLabels'><%= task.name %></p>
              <p class='uTaskLabels'><%= task.date %></p>
              <p class='uTaskLabels'><%= User.find(task.helper_id).first_name %> <%= User.find(task.helper_id).last_name %></p> 
              <p class='uTaskView' id='uViewTask'>
                <% if task.rated_by_client? %>
                  <%= link_to 'View', show_task_info_path(task.id, task.client_id), class: 'uTaskViewBtn'%>
                <% else %>
                  <%= link_to 'Rate', get_rate_helper_path(task.id, task.helper_id), class: 'uTaskViewBtn'%>
                <%end%>
              </p>
            </div>
          <%end%>
        <%end%> 
      </div>
    </div>
</div>

<script>
  var open = document.getElementById("open");
  var onGoing = document.getElementById("onGoing");
  var done = document.getElementById("history");
  var slideBtn = document.getElementById("slideBtn");
  var bOpen = document.getElementById("bOpen");
  var bOnGoing = document.getElementById("bOnGoing");
  var bHistory = document.getElementById("bHistory");
  var applicantListModal = document.getElementById("applicantsForm");
  var applicantListBtn = document.getElementById('listApplicantsBtn');
  var applicantListClose = document.getElementsByClassName("close")[0];

  function Open () {
    open.style.display = 'block';
    onGoing.style.display = 'none';
    done.style.display = 'none';
    slideBtn.style.left = '0%';
    bOpen.style.color = 'white'
    bOnGoing.style.color = 'black'
    bHistory.style.color = 'black'
  }

  function Going () {
    open.style.display = 'none';
    onGoing.style.display = 'block';
    done.style.display = 'none';
    slideBtn.style.left = '33.3%';
    bOpen.style.color = 'black'
    bOnGoing.style.color = 'white'
    bHistory.style.color = 'black'
  }

  function History () {
    open.style.display = 'none';
    onGoing.style.display = 'none';
    done.style.display = 'block';
    slideBtn.style.left = '67.3%';
    bOpen.style.color = 'black'
    bOnGoing.style.color = 'black'
    bHistory.style.color = 'white'
  }

  applicantListBtn.onclick = function() {
    applicantListModal.style.display = "block";
  }

  applicantListClose.onclick = function() {
    applicantListModal.style.display = "none";
  }

  window.onclick = function(event) {
    if (event.target == applicantListModal) {
      applicantListModal.style.display = "none";
    }
  }
</script>

app/views/user/show.html.erb
<div class='adminIndexContainer'>
  <div class='aHeaderContainer'>
    <h2 class='aHeader'>Account Information</h2>
  </div>

  <div>
    <hr class='aLine'>
  </div>
    
  <div class='aUserContainer'>
    <div>
      <img src="../assets/user_proxy_picture.png"/>
    </div>

    <div class='aInfoContainer'>
      <div class='aDetailContainer'>
        <p class='aInfoLabel'>First Name:</p>
        <p class='aInfoDetail'><%= @user.first_name %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Last Name: </p> 
        <p class='aInfoDetail'><%= @user.last_name %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Email: </p>
        <p class='aInfoDetail'><%= @user.email %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Mobile Number: </p>
        <p class='aInfoDetail'><%= @user.mobile_number %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>User Type: </p>
        <p class='aInfoDetail'> 
          <% if @user.helper == true %>
            Helper 
          <%else%> 
            Client
          <%end%>
        </p>
      </div>
    
      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Status: </p>
        <p class='aInfoDetail'><%= @user.user_status %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Balance: </p>
        <p class='aInfoDetail'><%= @user.balance %></p>
      </div>

      <div class='aDetailContainer'>
        <p class='aInfoLabel'>Rating: </p>
        <p class='aInfoDetail'>
          <% array = @user.rating.to_a %>
            <% if array.length == 0 %>
              <% ave = 0 %>
            <% else %>
              <% ave = array.sum/array.length %>
            <% end %>
          <%= ave %>/5
        </p>
      </div>

      <div>        
        <%= link_to 'Edit', edit_user_registration_path(@user.id), class: "btn btn-outline-dark btn-sm" %>
      </div>
        <%= link_to 'Back' , :back %>
    </div>
  </div>
</div>